[project]
name = "2025-05-02-pydanticai-rxpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-ai>=0.1.9",
    "reactivex>=4.0.4",
]
